name: 'Deploy Latest jabber:'
description: 'Deploy Latest JAR'

runs:
  using: "composite"
  
  steps:
    - name: Change to commit
      run: |
        git checkout ${{ inputs.commit }}
      shell: bash

    - name: Echo prueba
      run: cat ./todo
      shell: bash